export const layouthomeContent = {
  nav: {
    menu: 'MENÚ',
    home: 'INICIO',
    about: 'NOSOTROS',
    hairTransplantation: 'Trasplante Capilar',
    patientResources: 'Recursos para Pacientes',
    hairLossHistory: 'Historial de Pérdida Capilar',
    gallery: 'Galería',
    blogs: 'BLOGS',
    contact: 'contacto',
    videos: 'VIDEOS',
    hairTransplantMethodHeading: 'método de trasplante capilar:',
    hairTransplantHeading: 'trasplante capilar:',
    patientResourcesHeading: 'Recursos para Pacientes:',
    overview: 'Resumen',
    virtualConsultation: 'Consulta Virtual',
    methods: {
      artas: 'Restauración Capilar Robótica ARTAS iX',
      fue: 'Trasplante Capilar FUE',
      fut: 'Trasplante Capilar de Unidades Foliculares (FUT)',
      futShort: 'Trasplante Capilar FUT',
      prp: 'Tratamiento de Pérdida Capilar con PRP',
      dhi: 'Implantación Capilar Directa (DHI)',
      dhiShort: 'DHI',
      smp: 'Micropigmentación del Cuero Cabelludo',
      faq: 'Preguntas Frecuentes sobre Restauración Capilar',
    },
    transplantTypes: {
      male: 'Trasplantes Capilares Masculinos',
      female: 'Trasplantes Capilares Femeninos',
      facial: 'Trasplantes de Vello Facial',
      eyebrow: 'Trasplante de Cejas',
    },
    resources: {
      consultation: 'Consulta de Trasplante Capilar',
      cost: 'Costo del Trasplante Capilar',
      stages: 'Etapas de la Pérdida Capilar',
      financing: 'Financiamiento',
    },
    mobile: {
      home: 'Inicio',
      about: 'Nosotros',
      blogs: 'Blogs',
      contact: 'Contacto',
      videos: 'Videos',
    },
  },
  footer: {
    consultation: {
      heading: 'Programar una\u00a0Consulta',
      description:
        'Si está interesado en nuestros procedimientos de restauración capilar personalizados y cosechados a mano, su siguiente paso es una consulta privada con el Dr. Do. Durante este proceso, elaborará un plan honesto para ofrecerle el máximo alivio de la pérdida capilar.',
      cta: 'en la oficina',
    },
    contactUs: 'Contáctenos',
    contactUsUpper: 'CONTÁCTENOS',
    starsReviews: '4.3 Estrellas 56 Reseñas',
    emailUs: 'envíenos un correo',
    legal: {
      tagline: 'Especialistas en Restauración Capilar en Houston',
      copyright: '© 2026 Aesthetic Hair Restoration. Todos los derechos reservados.',
    },
  },
} as const;
