export const layouthomeContent = {
  nav: {
    menu: 'MENU',
    home: 'HOME',
    about: 'ABOUT',
    hairTransplantation: 'Hair Transplantation',
    patientResources: 'Patient Resources',
    hairLossHistory: 'Hair Loss History',
    gallery: 'Gallery',
    blogs: 'BLOGS',
    contact: 'contact',
    videos: 'VIDEOS',
    hairTransplantMethodHeading: 'hair transplant method:',
    hairTransplantHeading: 'hair transplant:',
    patientResourcesHeading: 'Patient Resources:',
    overview: 'Over View',
    virtualConsultation: 'Virtual Consultation',
    methods: {
      artas: 'ARTAS iX Robotic Hair Restoration',
      fue: 'FUE Hair Transplant',
      fut: 'Follicular Unit Hair Transplant (FUT)',
      futShort: 'FUT Hair Transplant',
      prp: 'PRP Hair Loss Treatment',
      dhi: 'Direct Hair Implantation (DHI)',
      dhiShort: 'DHI',
      smp: 'Scalp Micropigmentation',
      faq: 'Hair Restoration FAQ',
    },
    transplantTypes: {
      male: 'Male Hair Transplants',
      female: 'Female Hair Transplants',
      facial: 'Facial Hair Transplants',
      eyebrow: 'Eyebrow Transplant',
    },
    resources: {
      consultation: 'Hair Transplant Consultation',
      cost: 'Hair Transplant Cost',
      stages: 'Stages of Hair Loss',
      financing: 'Financing',
    },
    mobile: {
      home: 'Home',
      about: 'About',
      blogs: 'Blogs',
      contact: 'Contact',
      videos: 'Videos',
    },
  },
  footer: {
    consultation: {
      heading: 'Schedule a\u00a0Consultation',
      description:
        'If you are interested in our custom tailored, hand-harvested hair restoration procedures, your next step is a private consultation with Dr. Do. During this process, he will construct an honest plan to deliver maximum relief from hair loss.',
      cta: 'in-office',
    },
    contactUs: 'Contact us',
    contactUsUpper: 'CONTACT US',
    starsReviews: '4.3 Stars 56 Reviews',
    emailUs: 'email us',
    legal: {
      tagline: 'Houston Hair Restoration Specialists',
      copyright: '© 2026 Aesthetic Hair Restoration. All Rights Reserved.',
    },
  },
} as const;
