export const navContent = {
  menu: 'MENÚ',
  home: 'INICIO',
  about: 'NOSOTROS',
  hairTransplantation: 'Trasplante Capilar',
  patientResources: 'Recursos para Pacientes',
  hairLossHistory: 'Historial de Pérdida Capilar',
  gallery: 'Galería',
  blogs: 'BLOGS',
  contact: 'contacto',
  videos: 'VIDEOS',
  hairTransplantMethodHeading: 'método de trasplante capilar:',
  hairTransplantHeading: 'trasplante capilar:',
  patientResourcesHeading: 'Recursos para Pacientes:',
  overview: 'Resumen',
  virtualConsultation: 'Consulta Virtual',
  methods: {
    artas: 'Restauración Capilar Robótica ARTAS iX',
    fue: 'Trasplante Capilar FUE',
    fut: 'Trasplante Capilar de Unidades Foliculares (FUT)',
    futShort: 'Trasplante Capilar FUT',
    prp: 'Tratamiento de Pérdida Capilar con PRP',
    dhi: 'Implantación Capilar Directa (DHI)',
    dhiShort: 'DHI',
    smp: 'Micropigmentación del Cuero Cabelludo',
    faq: 'Preguntas Frecuentes sobre Restauración Capilar',
  },
  transplantTypes: {
    male: 'Trasplantes Capilares Masculinos',
    female: 'Trasplantes Capilares Femeninos',
    facial: 'Trasplantes de Vello Facial',
    eyebrow: 'Trasplante de Cejas',
  },
  resources: {
    consultation: 'Consulta de Trasplante Capilar',
    cost: 'Costo del Trasplante Capilar',
    stages: 'Etapas de la Pérdida Capilar',
    financing: 'Financiamiento',
  },
  mobile: {
    home: 'Inicio',
    about: 'Nosotros',
    blogs: 'Blogs',
    contact: 'Contacto',
    videos: 'Videos',
  },
} as const;
